export const SERVICES_ID = 'services'
export const DEPENDENCIES_ID = 'dependencies'
export const IMPACTS_ID = 'impacts'
export const DEPENDENCIES_SERVICES_ID = 'dependencies-services'
export const DEPENDENCIES_ASSETS_ID = 'dependencies-assets'
export const IMPACTS_IMPACT_DRIVERS_ID = 'impacts-impact-drivers'
export const IMPACTS_ASSETS_ID = 'impacts-assets'