FROM ruby:3.1.0

RUN apt-get update -qq && apt-get install -y postgresql-client apt-transport-https yarn libxml2-dev build-essential libpq-dev

RUN mkdir /railsapp
WORKDIR /railsapp
RUN gem install bundler:2.3.14

#RUN bundle config set --local path 'vendor/bundle'

COPY Gemfile /railsapp/Gemfile
COPY Gemfile.lock /railsapp/Gemfile.lock
RUN bundle install
COPY . /railsapp

EXPOSE 3000

CMD ["rails", "server", "-b", "0.0.0.0"]
